enum Permission {
  AUDIT_READ = 'AUDIT_READ',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  USER_CREATE = 'USER_CREATE',
  USER_DELETE = 'USER_DELETE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export default Permission;
